using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace  ChallengeHelpers{
internal class ChallengeHelper
{
 

  
    public List<ChallengeData> GenerateChallenges()
{

   
            List<ChallengeData> challengeData = new List<ChallengeData>();
            List<string> challengeTypes = new List<string>{"Consistency","Pace","Endurance"};
            List<int> upperBound = new List<int> {5,2,10};
            List<int> lowerBound = new List<int> {2,1,5};
     
            List<Car> carList = new List<Car>{
              new Car { id= 1, brand= "Abarth", name= "1500 Biposto Bertone B.A.T 1", category= "N 100" },
  new Car { id= 2, brand= "Abarth", name= "500", category= "N 100" },
  new Car { id= 3, brand= "Alfa Romeo", name= "4C Gr.3", category= "Gr.3" },
  new Car { id= 4, brand= "Alfa Romeo", name= "4C Gr.4", category= "Gr.4" },
  new Car { id= 5, brand= "Alfa Romeo", name= "4C Launch Edition", category= "N 200" },
  new Car { id= 6, brand= "Alfa Romeo", name= "GIULIA TZ2 carrozzata da ZAGATO CN.AR750106", category= "Gr.X" },
  new Car { id= 7, brand= "Alfa Romeo", name= "MiTo 1.4 T Sport", category= "N 200" },
  new Car { id= 8, brand= "Alfa Romeo", name= "4C Gr.3 Road Car", category= "N 500" },
  new Car { id= 9, brand= "Alpine", name= "A110 1600S", category= "N 100" },
  new Car { id= 10, brand= "Alpine", name= "A110 Première Édition", category= "N 300" },
  new Car { id= 11, brand= "Alpine", name= "Alpine Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 12, brand= "Alpine", name= "Alpine Vision Gran Turismo 2017", category= "Gr.1" },
  new Car { id= 13, brand= "Alpine", name= "Alpine Vision Gran Turismo Race Mode", category= "Gr.X" },
  new Car { id= 14, brand= "Amuse", name= "Amuse S2000 GT1 Turbo", category= "N 600" },
  new Car { id= 15, brand= "Aston Martin", name= "Aston Martin DP-100 Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 16, brand= "Aston Martin", name= "Aston Martin Vulcan", category= "Gr.X" },
  new Car { id= 17, brand= "Aston Martin", name= "DB11", category= "N 600" },
  new Car { id= 18, brand= "Aston Martin", name= "DB3S CN.1", category= "Gr.X" },
  new Car { id= 19, brand= "Aston Martin", name= "DBR9 GT1", category= "Gr.3" },
  new Car { id= 20, brand= "Aston Martin", name= "One-77", category= "N 800" },
  new Car { id= 21, brand= "Aston Martin", name= "V12 Vantage GT3", category= "Gr.3" },
  new Car { id= 22, brand= "Aston Martin", name= "V8 Vantage S", category= "N 400" },
  new Car { id= 23, brand= "Aston Martin", name= "Vantage Gr.4", category= "Gr.4" },
  new Car { id= 24, brand= "Audi", name= "Audi e-tron Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 25, brand= "Audi", name= "Audi R18 (Audi Sport Team Joest)", category= "Gr.1" },
  new Car { id= 26, brand= "Audi", name= "Audi R18 TDI (Audi Sport Team Joest)", category= "Gr.1" },
  new Car { id= 27, brand= "Audi", name= "Audi R8 LMS (Audi Sport Team WRT)", category= "Gr.3" },
  new Car { id= 28, brand= "Audi", name= "Audi Sport quattro S1 Pikes Peak", category= "Gr.B Rally" },
  new Car { id= 29, brand= "Audi", name= "Audi Vision Gran Turismo", category= "Gr.1" },
  new Car { id= 30, brand= "Audi", name= "R8 4.2 FSI R tronic", category= "N 400" },
  new Car { id= 31, brand= "Audi", name= "TT cup", category= "Gr.4" },
  new Car { id= 32, brand= "Audi", name= "TT Coupé 3.2 quattro", category= "N 200" },
  new Car { id= 33, brand= "Audi", name= "TTS Coupé", category= "N 300" },
  new Car { id= 34, brand= "BMW", name= "BMW i3", category= "N 200" },
  new Car { id= 35, brand= "BMW", name= "BMW M3 Coupé", category= "N 300" },
  new Car { id= 36, brand= "BMW", name= "BMW M3 Coupé", category= "N 400" },
  new Car { id= 37, brand= "BMW", name= "BMW M3 GT (BMW Motorsport)", category= "Gr.3" },
  new Car { id= 38, brand= "BMW", name= "BMW M3 Sport Evolution", category= "N 200" },
  new Car { id= 39, brand= "BMW", name= "BMW M4 Coupé", category= "N 400" },
  new Car { id= 40, brand= "BMW", name= "BMW M4 Gr.4", category= "Gr.4" },
  new Car { id= 41, brand= "BMW", name= "BMW M4 Safety Car", category= "Gr.X" },
  new Car { id= 42, brand= "BMW", name= "BMW M6 GT3 (Walkenhorst Motorsport)", category= "Gr.3" },
  new Car { id= 43, brand= "BMW", name= "BMW M6 GT3 M Power Livery", category= "Gr.3" },
  new Car { id= 44, brand= "BMW", name= "BMW Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 45, brand= "BMW", name= "BMW Z4 GT3", category= "Gr.3" },
  new Car { id= 46, brand= "BMW", name= "BMW Z8", category= "N 400" },
  new Car { id= 47, brand= "Bugatti", name= "Bugatti Vision Gran Turismo", category= "Gr.X / Gr.1" },
  new Car { id= 48, brand= "Bugatti", name= "Veyron 16.4", category= "N1000" },
  new Car { id= 49, brand= "Bugatti", name= "Veyron Gr.4", category= "Gr.4" },
  new Car{ id= 50, brand= "Chaparral", name= "Chevrolet Chaparral 2X Vision Gran Turismo", category= "Gr.X" },
  new Car{ id= 51, brand= "Chevrolet", name= "Camaro SS", category= "N 500" },
  new Car{ id= 52, brand= "Chevrolet", name= "Camaro Z28", category= "N 300" },
  new Car{ id= 53, brand= "Chevrolet", name= "Camaro ZL1 1LE Package", category= "N 700" },
  new Car{ id= 54, brand= "Chevrolet", name= "Corvette C7 Gr.3", category= "Gr.3" },
  new Car{ id= 55, brand= "Chevrolet", name= "Corvette C7 Gr.3 Road Car", category= "N 500" },
  new Car{ id= 56, brand= "Chevrolet", name= "Corvette C7 Gr.4", category= "Gr.4" },
  new Car{ id= 57, brand= "Chevrolet", name= "Corvette Stingray (C7)", category= "N 500" },
  new Car{ id= 58, brand= "Chevrolet", name= "Corvette Stingray Convertible (C3)", category= "N 300" },
  new Car{ id= 59, brand= "Chevrolet", name= "Corvette StingRay Racer Concept", category= "Gr.X" },
  new Car{ id= 60, brand= "Chevrolet", name= "Corvette Sting Ray Sport Coupe (C2)", category= "N 200" },
  new Car{ id= 61, brand= "Citroën", name= "DS3 Racing", category= "N 200" },
  new Car{ id= 62, brand= "Citroën", name= "GT by Citroën Gr.4", category= "Gr.4" },
  new Car{ id= 63, brand= "Citroën", name= "GT by Citroën Race Car (Gr.3)", category= "Gr.3" },
  new Car{ id= 64, brand= "Citroën", name= "GT by Citroën Road Car", category= "N 500" },
  new Car{ id= 65, brand= "Daihatsu", name= "Copen Active Top", category= "N 100" },
  new Car{ id= 66, brand= "Daihatsu", name= "DAIHATSU COPEN RJ Vision Gran Turismo", category= "Gr.X" },
  new Car{ id= 67, brand= "Dallara", name= "SF19 Super Formula / Honda", category= "Gr.X" },
  new Car{ id= 68, brand= "Dallara", name= "SF19 Super Formula / Toyota", category= "Gr.X" },
  new Car{ id= 69, brand= "De Tomaso", name= "Pantera", category= "N 300" },
  new Car{ id= 70, brand= "Dodge", name= "Challenger R/T", category= "N 400" },
  new Car{ id= 71, brand= "Dodge", name= "Dodge Charger SRT Hellcat", category= "N 700" },
  new Car{ id= 72, brand= "Dodge", name= "Dodge Charger SRT Hellcat Safety Car", category= "Gr.X" },
  new Car{ id= 73, brand= "Dodge", name= "SRT Tomahawk GTS-R Vision Gran Turismo", category= "Gr.X" },
  new Car{ id= 74, brand= "Dodge", name= "SRT Tomahawk S Vision Gran Turismo", category= "Gr.X" },
  new Car{ id= 75, brand= "Dodge", name= "SRT Tomahawk Vision Gran Turismo (Gr.1)", category= "Gr.1" },
  new Car{ id= 76, brand= "Dodge", name= "SRT Tomahawk X Vision Gran Turismo", category= "Gr.X" },
  new Car{ id= 77, brand= "Dodge", name= "Super Bee", category= "N 300" },
  new Car{ id= 78, brand= "Dodge", name= "Viper Gr.4", category= "Gr.4" },
  new Car{ id= 79, brand= "Dodge", name= "Viper GTS", category= "N 600" },
  new Car{ id= 80, brand= "Dodge", name= "Viper GTS", category= "N 500" },
  new Car{ id= 81, brand= "Dodge", name= "Viper SRT10 Coupe", category= "N 500" },
  new Car{ id= 82, brand= "Dodge", name= "Viper SRT GT3-R", category= "Gr.3" },
  new Car{ id= 83, brand= "Ferrari", name= "250 GT Berlinetta passo corto CN.2521", category= "N 300" },
  new Car { id= 84, brand= "Ferrari", name= "250 GTO CN.3729GT", category= "Gr.X" },
  new Car { id= 85, brand= "Ferrari", name= "330 P4", category= "Gr.X" },
  new Car { id= 86, brand= "Ferrari", name= "365 GTB4", category= "N 400" },
  new Car { id= 87, brand= "Ferrari", name= "458 Italia", category= "N 600" },
  new Car { id= 88, brand= "Ferrari", name= "458 Italia Gr.4", category= "Gr.4" },
  new Car { id= 89, brand= "Ferrari", name= "458 Italia GT3", category= "Gr.3" },
  new Car { id= 90, brand= "Ferrari", name= "512 BB", category= "N400" },
  new Car { id= 91, brand= "Ferrari", name= "Dino 246 GT", category= "N200" },
  new Car { id= 92, brand= "Ferrari", name= "Enzo Ferrari", category= "N 700" },
  new Car { id= 93, brand= "Ferrari", name= "F40", category= "N 500" },
  new Car { id= 94, brand= "Ferrari", name= "F50", category= "N 500" },
  new Car { id= 95, brand= "Ferrari", name= "GTO", category= "N 400" },
  new Car { id= 96, brand= "Ferrari", name= "LaFerrari", category= "N1000" },
  new Car { id= 97, brand= "Fiat", name= "500 1.2 8V Lounge SS", category= "N100" },
  new Car { id= 98, brand= "Fiat", name= "500 F", category= "N100" },
  new Car { id= 99, brand= "Fittipaldi Motors", name= "Fittipaldi EF7 Vision Gran Turismo by Pininfarina", category= "Gr.X" },
  new Car { id= 100, brand= "Ford", name= "F-150 SVT Raptor", category= "N 400" },
  new Car { id= 101, brand= "Ford", name= "Focus Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 102, brand= "Ford", name= "Focus ST", category= "N 300" },
  new Car { id= 103, brand= "Ford", name= "Ford GT", category= "N 600" },
  new Car { id= 104, brand= "Ford", name= "Ford GT 17", category= "N 700" },
  new Car { id= 105, brand= "Ford", name= "Ford GT LM Spec II Test Car", category= "Gr.3" },
  new Car { id= 106, brand= "Ford", name= "GT40 Mark I", category= "N 400" },
  new Car { id= 107, brand= "Ford", name= "Mark IV Race Car", category= "Gr.X" },
  new Car { id= 108, brand= "Ford", name= "Mustang Gr.3", category= "Gr.3" },
  new Car { id= 109, brand= "Ford", name= "Mustang Gr.4", category= "Gr.4" },
  new Car { id= 110, brand= "Ford", name= "Mustang Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 111, brand= "Ford", name= "Mustang GT Premium Fastback", category= "N 400" },
  new Car { id= 112, brand= "Ford", name= "Mustang Gr.3 Road Car", category= "N 500" },
  new Car { id= 113, brand= "Ford", name= "Mustang Mach 1", category= "N 300" },
  new Car { id= 114, brand= "Gran Turismo", name= "F1500T-A", category= "Gr.X" },
  new Car { id= 115, brand= "Gran Turismo", name= "Gran Turismo Racing Kart 125 Shifter", category= "Gr.X" },
  new Car { id= 116, brand= "Gran Turismo", name= "Gran Turismo Red Bull X2014 Junior", category= "Gr.X" },
  new Car { id= 117, brand= "Gran Turismo", name= "Gran Turismo Red Bull X2014 Standard", category= "Gr.X" },
  new Car { id= 118, brand= "Gran Turismo", name= "Gran Turismo Red Bull X2019 Competition", category= "Gr.X" },
  new Car { id= 119, brand= "Greddy", name= "Fugu Z", category= "N 300" },
  new Car { id= 120, brand= "GT Awards (SEMA)", name= "Chris Holstrom Concepts", category= "N 700" },
  new Car { id= 121, brand= "GT Awards (SEMA)", name= "Mach Forty", category= "N 800" },
  new Car { id= 122, brand= "Honda", name= "Beat", category= "N 100" },
  new Car { id= 123, brand= "Honda", name= "Civic Type R (EK)", category= "N 200" },
  new Car { id= 124, brand= "Honda", name= "Civic Type R (FK2)", category= "N 300" },
  new Car { id= 125, brand= "Honda", name= "EPSON NSX", category= "Gr.2" },
  new Car { id= 126, brand= "Honda", name= "Fit Hybrid", category= "N 100" },
  new Car { id= 127, brand= "Honda", name= "Honda Project 2&4 powered by RC213V", category= "Gr.X" },
  new Car { id= 128, brand= "Honda", name= "Honda Sports Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 129, brand= "Honda", name= "Integra Type R (DC2)", category= "N 200" },
  new Car { id= 130, brand= "Honda", name= "NSX", category= "N 600" },
  new Car { id= 131, brand= "Honda", name= "NSX Gr.3", category= "Gr.3" },
  new Car { id= 132, brand= "Honda", name= "NSX Gr.4", category= "Gr.4" },
  new Car { id= 133, brand= "Honda", name= "NSX Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 134, brand= "Honda", name= "NSX Type R", category= "N 300" },
  new Car { id= 135, brand= "Honda", name= "RAYBRIG NSX CONCEPT-GT", category= "Gr.2" },
  new Car { id= 136, brand= "Honda", name= "S2000", category= "N 200" },
  new Car { id= 137, brand= "Honda", name= "S660", category= "N 100" },
  new Car { id= 138, brand= "Honda", name= "S800", category= "N 100" },
  new Car { id= 139, brand= "Hyundai", name= "Genesis Coupe 3.8 Track", category= "N 300" },
  new Car { id= 140, brand= "Hyundai", name= "Genesis Gr.3", category= "Gr.3" },
  new Car { id= 141, brand= "Hyundai", name= "Genesis Gr.4", category= "Gr.4" },
  new Car { id= 142, brand= "Hyundai", name= "Genesis Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 143, brand= "Hyundai", name= "HYUNDAI N 2025 Vision Gran Turismo", category= "Gr.X / Gr.1" },
  new Car { id= 144, brand= "Infiniti", name= "INFINITI CONCEPT Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 145, brand= "Jaguar", name= "D-type", category= "Gr.X" },
  new Car { id= 146, brand= "Jaguar", name= "E-type Coupé", category= "N 300" },
  new Car { id= 147, brand= "Jaguar", name= "F-type Gr.3", category= "Gr.3" },
  new Car { id= 148, brand= "Jaguar", name= "F-type Gr.4", category= "Gr.4" },
  new Car { id= 149, brand= "Jaguar", name= "F-type R Coupé", category= "N 500" },
  new Car { id= 150, brand= "Jaguar", name= "Jaguar Vision Gran Turismo Coupé", category= "Gr.X" },
  new Car { id= 151, brand= "Jaguar", name= "Jaguar XJ13", category= "Gr.X" },
  new Car { id= 152, brand= "Jaguar", name= "Jaguar XJR-9", category= "Gr.1" },
  new Car { id= 153, brand= "KTM", name= "X-BOW R", category= "N 300" },
  new Car { id= 154, brand= "Lamborghini", name= "2015 Lamborghini Huracán GT3", category= "Gr.3" },
  new Car { id= 155, brand= "Lamborghini", name= "Aventador LP 700-4", category= "N 700" },
  new Car { id= 156, brand= "Lamborghini", name= "Aventador LP 750-4 Superveloce", category= "N 800" },
  new Car { id= 157, brand= "Lamborghini", name= "Countach 25th Anniversary", category= "N 500" },
  new Car { id= 158, brand= "Lamborghini", name= "Countach LP400", category= "N 400" },
  new Car { id= 159, brand= "Lamborghini", name= "Diablo GT", category= "N 600" },
  new Car { id= 160, brand= "Lamborghini", name= "Huracán Gr.4", category= "Gr.4" },
  new Car { id= 161, brand= "Lamborghini", name= "Huracán LP 610-4", category= "N 600" },
  new Car { id= 162, brand= "Lamborghini", name= "Miura P400 Bertone Prototype CN.0706", category= "N 400" },
  new Car { id= 163, brand= "Lamborghini", name= "Veneno", category= "N 800" },
  new Car { id= 164, brand= "Lancia", name= "DELTA HF Integrale Evoluzione", category= "N 200" },
  new Car { id= 165, brand= "Lancia", name= "Stratos", category= "N 200" },
  new Car { id= 166, brand= "Lexus", name= "au TOM S RC F", category= "Gr.2" },
  new Car { id= 167, brand= "Lexus", name= "LC500", category= "N 500" },
  new Car { id= 168, brand= "Lexus", name= "LEXUS LF-LC GT “Vision Gran Turismo”", category= "Gr.X" },
  new Car { id= 169, brand= "Lexus", name= "PETRONAS TOM S SC430", category= "Gr.2" },
  new Car { id= 170, brand= "Lexus", name= "RC F", category= "N 500" },
  new Car { id= 171, brand= "Lexus", name= "RC F Gr.4", category= "Gr.4" },
  new Car { id= 172, brand= "Lexus", name= "RC F GT3 (Emil Frey Racing)", category= "Gr.3" },
  new Car { id= 173, brand= "Lexus", name= "RC F GT3 prototype (Emil Frey Racing)", category= "Gr.3" },
  new Car { id= 174, brand= "Maserati", name= "GranTurismo S", category= "N 400" },
  new Car { id= 175, brand= "Mazda", name= "Atenza Gr.3", category= "Gr.3" },
  new Car { id= 176, brand= "Mazda", name= "Atenza Gr.3 Road Car", category= "N 500" },
  new Car { id= 177, brand= "Mazda", name= "Atenza Gr.4", category= "Gr.4" },
  new Car { id= 178, brand= "Mazda", name= "Atenza Sedan XD L Package", category= "N 200" },
  new Car { id= 179, brand= "Mazda", name= "Demio XD Touring", category= "N 100" },
  new Car { id= 180, brand= "Mazda", name= "Eunos Roadster (NA Special Package)", category= "N 200" },
  new Car { id= 181, brand= "Mazda", name= "LM55 Vision Gran Turismo", category= "Gr.X / Gr.1" },
  new Car { id= 182, brand= "Mazda", name= "Mazda 787B", category= "Gr.1" },
  new Car { id= 183, brand= "Mazda", name= "Roadster S (ND)", category= "N 100" },
  new Car { id= 184, brand= "Mazda", name= "Roadster Touring Car", category= "N 200" },
  new Car { id= 185, brand= "Mazda", name= "RX500", category= "N 300" },
  new Car { id= 186, brand= "Mazda", name= "RX-7 GT-X (FC)", category= "N 200" },
  new Car { id= 187, brand= "Mazda", name= "RX-7 Spirit R Type A (FD)", category= "N 300" },
  new Car { id= 188, brand= "Mazda", name= "RX-VISION GT3 CONCEPT", category= "Gr.3" },
  new Car { id= 189, brand= "McLaren", name= "650S Coupe", category= "N 700" },
  new Car { id= 190, brand= "McLaren", name= "650S Gr.4", category= "Gr.4" },
  new Car { id= 191, brand= "McLaren", name= "650S GT3", category= "Gr.3" },
  new Car { id= 192, brand= "McLaren", name= "McLaren F1", category= "N 600" },
  new Car { id= 193, brand= "McLaren", name= "McLaren F1 GTR - BMW (Kokusai Kaihatsu UK Racing)", category= "Gr.3" },
  new Car { id= 194, brand= "McLaren", name= "McLaren Ultimate Vision Gran Turismo", category= "Gr.X / Gr.1" },
  new Car { id= 195, brand= "McLaren", name= "MP4-12C", category= "N 600" },
  new Car { id= 196, brand= "McLaren", name= "P1 GTR", category= "Gr.X" },
  new Car { id= 197, brand= "Mercedes-Benz", name= "300 SEL 6.8 AMG", category= "N 400" },
  new Car { id= 198, brand= "Mercedes-Benz", name= "A 45 AMG 4MATIC", category= "Gr.X" },
  new Car { id= 199, brand= "Mercedes-Benz", name= "Mercedes-AMG F1 W08 EQ Power+", category= "Gr.X" },
  new Car { id= 200, brand= "Mercedes-Benz", name= "Mercedes-AMG F1 W08 EQ Power+ (Color Variation)", category= "Gr.X" },
  new Car { id= 201, brand= "Mercedes-Benz", name= "Mercedes-AMG GT S", category= "N 500" },
  new Car { id= 202, brand= "Mercedes-Benz", name= "Mercedes-AMG GT Safety Car", category= "Gr.X" },
  new Car { id= 203, brand= "Mercedes-Benz", name= "Mercedes-AMG GT3 (AMG-Team HTP-Motorsport)", category= "Gr.3" },
  new Car { id= 204, brand= "Mercedes-Benz", name= "Mercedes-Benz AMG Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 205, brand= "Mercedes-Benz", name= "Mercedes-Benz AMG Vision Gran Turismo Racing Series", category= "Gr.X" },
  new Car { id= 206, brand= "Mercedes-Benz", name= "Sauber Mercedes C9", category= "Gr.1" },
  new Car { id= 207, brand= "Mercedes-Benz", name= "SLR McLaren", category= "N 600" },
  new Car { id= 208, brand= "Mercedes-Benz", name= "SLS AMG", category= "N 600" },
  new Car { id= 209, brand= "Mercedes-Benz", name= "SLS AMG Gr.4", category= "Gr.4" },
  new Car { id= 210, brand= "Mercedes-Benz", name= "SLS AMG GT3", category= "Gr.3" },
  new Car { id= 211, brand= "MINI", name= "MINI Clubman Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 212, brand= "MINI", name= "MINI Cooper S", category= "N 200" },
  new Car { id= 213, brand= "MINI", name= "Mini-Cooper S", category= "N 100" },
  new Car { id= 214, brand= "Mitsubishi", name= "Concept XR-PHEV EVOLUTION Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 215, brand= "Mitsubishi", name= "GTO Twin Turbo", category= "N 300" },
  new Car { id= 216, brand= "Mitsubishi", name= "Lancer Evolution Final Edition", category= "N 300" },
  new Car { id= 217, brand= "Mitsubishi", name= "Lancer Evolution Final Edition Gr.3", category= "Gr.3" },
  new Car { id= 218, brand= "Mitsubishi", name= "Lancer Evolution Final Edition Gr.4", category= "Gr.4" },
  new Car { id= 219, brand= "Mitsubishi", name= "Lancer Evolution Final Edition Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 220, brand= "Mitsubishi", name= "Lancer Evolution Final Edition Gr.B Road Car", category= "N 500" },
  new Car { id= 221, brand= "Mitsubishi", name= "Lancer Evolution IV GSR", category= "N 300" },
  new Car { id= 222, brand= "Nissan", name= "180SX Type X", category= "N 200" },
  new Car { id= 223, brand= "Nissan", name= "Fairlady Z 300ZX TwinTurbo 2 seater (Z32)", category= "N 300" },
  new Car { id= 224, brand= "Nissan", name= "Fairlady Z Version S (Z33)", category= "N 300" },
  new Car { id= 225, brand= "Nissan", name= "GT-R Gr.4", category= "Gr.4" },
  new Car { id= 226, brand= "Nissan", name= "GT-R Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 227, brand= "Nissan", name= "GT-R LM NISMO", category= "Gr.1" },
  new Car { id= 228, brand= "Nissan", name= "GT-R NISMO GT3 N24 Schulze Motorsport", category= "Gr.3" },
  new Car { id= 229, brand= "Nissan", name= "GT-R Premium edition", category= "N 600" },
  new Car { id= 230, brand= "Nissan", name= "GT-R Safety Car", category= "Gr.X" },
  new Car { id= 231, brand= "Nissan", name= "MOTUL AUTECH GT-R", category= "Gr.2" },
  new Car { id= 232, brand= "Nissan", name= "NISSAN CONCEPT 2020 Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 233, brand= "Nissan", name= "Nissan GT-R NISMO", category= "N 600" },
  new Car { id= 234, brand= "Nissan", name= "R92CP", category= "Gr.1" },
  new Car { id= 235, brand= "Nissan", name= "Skyline GT-R V・spec (R33)", category= "N 300" },
  new Car { id= 236, brand= "Nissan", name= "Skyline GT-R V・spec II (R32)", category= "N 300" },
  new Car { id= 237, brand= "Nissan", name= "Skyline GT-R V・spec II Nür (R34)", category= "N 300" },
  new Car { id= 238, brand= "Nissan", name= "Silvia Ks Dia Selection (S13)", category= "N 200" },
  new Car { id= 239, brand= "Nissan", name= "XANAVI NISMO GT-R", category= "Gr.2" },
  new Car { id= 240, brand= "Pagani", name= "Huayra", category= "N 700" },
  new Car { id= 241, brand= "Pagani", name= "Zonda R", category= "Gr.X" },
  new Car { id= 242, brand= "Peugeot", name= "208 GTi by Peugeot Sport", category= "N 200" },
  new Car { id= 243, brand= "Peugeot", name= "Peugeot 908 HDi FAP - Team Peugeot Total", category= "Gr.1" },
  new Car { id= 244, brand= "Peugeot", name= "Peugeot L500R HYbrid Vision Gran Turismo, 2017", category= "Gr.X" },
  new Car { id= 245, brand= "Peugeot", name= "Peugeot L750R HYbrid Vision Gran Turismo, 2017", category= "Gr.1" },
  new Car { id= 246, brand= "Peugeot", name= "PEUGEOT Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 247, brand= "Peugeot", name= "PEUGEOT Vision Gran Turismo (Gr.3)", category= "Gr.3" },
  new Car { id= 248, brand= "Peugeot", name= "RCZ Gr.3", category= "Gr.3" },
  new Car { id= 249, brand= "Peugeot", name= "RCZ Gr.4", category= "Gr.4" },
  new Car { id= 250, brand= "Peugeot", name= "RCZ Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 251, brand= "Peugeot", name= "RCZ GT Line", category= "N 200" },
  new Car { id= 252, brand= "Plymouth", name= "XNR Ghia Roadster", category= "N 300" },
  new Car { id= 253, brand= "Pontiac", name= "Firebird Trans Am", category= "N 200" },
  new Car { id= 254, brand= "Porsche", name= "356 A/1500 GS GT Carrera Speedster", category= "N 100" },
  new Car { id= 255, brand= "Porsche", name= "911 Carrera RS Club Sport (993)", category= "N 300" },
  new Car { id= 256, brand= "Porsche", name= "911 GT3 RS (991)", category= "N 500" },
  new Car { id= 257, brand= "Porsche", name= "911 GT3 (996)", category= "N 400" },
  new Car { id= 258, brand= "Porsche", name= "911 GT3 (997)", category= "N 400" },
  new Car { id= 259, brand= "Porsche", name= "911 RSR (991)", category= "Gr.3" },
  new Car { id= 260, brand= "Porsche", name= "911 Turbo (930)", category= "N 300" },
  new Car { id= 261, brand= "Porsche", name= "962 C", category= "Gr.1" },
  new Car { id= 262, brand= "Porsche", name= "Cayman GT4 Clubsport", category= "Gr.4" },
  new Car { id= 263, brand= "Porsche", name= "Porsche 919 Hybrid (Porsche Team)", category= "Gr.1" },
  new Car { id= 264, brand= "Porsche", name= "Taycan Turbo S", category= "Gr.X" },
  new Car { id= 265, brand= "RE Amemiya", name= "FD3S RX-7", category= "N 400" },
  new Car { id= 266, brand= "Renault", name= "R8 Gordini", category= "Gr.X" },
  new Car { id= 267, brand= "Renault Sport", name= "Clio R.S. 220 EDC Trophy 15", category= "N 200" },
  new Car { id= 268, brand= "Renault Sport", name= "Clio R.S. 220 EDC Trophy 16", category= "N 200" },
  new Car { id= 269, brand= "Renault Sport", name= "Clio V6 24V", category= "N 200" },
  new Car { id= 270, brand= "Renault Sport", name= "Mégane Gr.4", category= "Gr.4" },
  new Car { id= 271, brand= "Renault Sport", name= "Mégane R.S. Trophy", category= "N 300" },
  new Car { id= 272, brand= "Renault Sport", name= "Mégane R.S. Trophy Safety Car", category= "Gr.X" },
  new Car { id= 273, brand= "Renault Sport", name= "Mégane Trophy", category= "Gr.4" },
  new Car { id= 274, brand= "Renault Sport", name= "R.S.01", category= "Gr.X" },
  new Car { id= 275, brand= "Renault Sport", name= "R.S.01 GT3", category= "Gr.3" },
  new Car { id= 276, brand= "RUF", name= "CTR3", category= "N 700" },
  new Car { id= 277, brand= "Shelby", name= "Shelby Cobra 427", category= "N 500" },
  new Car { id= 278, brand= "Shelby", name= "Shelby Cobra Daytona Coupe", category= "Gr.X" },
  new Car { id= 279, brand= "Shelby", name= "Shelby G.T.350", category= "N 300" },
  new Car { id= 280, brand= "Subaru", name= "BRZ S", category= "N 200" },
  new Car { id= 281, brand= "Subaru", name= "Falken Tire / Turn 14 Distribution BRZ", category= "Gr.X" },
  new Car { id= 282, brand= "Subaru", name= "Impreza 22B-STi Version", category= "N 300" },
  new Car { id= 283, brand= "Subaru", name= "Impreza Coupe WRX Type R STi Version VI", category= "N 300" },
  new Car { id= 284, brand= "Subaru", name= "SUBARU VIZIV GT Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 285, brand= "Subaru", name= "Subaru WRX STI Isle of Man Time Attack Car", category= "Gr.X" },
  new Car { id= 286, brand= "Subaru", name= "WRX Gr.3", category= "Gr.3" },
  new Car { id= 287, brand= "Subaru", name= "WRX Gr.4", category= "Gr.4" },
  new Car { id= 288, brand= "Subaru", name= "WRX Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 289, brand= "Subaru", name= "WRX STI Type S", category= "N 300" },
  new Car { id= 290, brand= "Subaru", name= "WRX Gr.B Road Car", category= "N 500" },
  new Car { id= 291, brand= "Suzuki", name= "Swift Sport", category= "N 100" },
  new Car { id= 292, brand= "Toyota", name= "86 GRMN", category= "N 200" },
  new Car { id= 293, brand= "Toyota", name= "86 GT Limited", category= "N 200" },
  new Car { id= 294, brand= "Toyota", name= "Corolla Levin 3door 1600GT APEX (AE86)", category= "N 100" },
  new Car { id= 295, brand= "Toyota", name= "Crown Athlete G", category= "N 300" },
  new Car { id= 296, brand= "Toyota", name= "Crown Athlete G Safety Car", category= "Gr.X" },
  new Car { id= 297, brand= "Toyota", name= "GR 86", category= "N 200" },
  new Car { id= 298, brand= "Toyota", name= "GR Supra Racing Concept", category= "Gr.3" },
  new Car { id= 299, brand= "Toyota", name= "GR Supra RZ", category= "N 300" },
  new Car { id= 300, brand= "Toyota", name= "GR Supra RZ20", category= "N 400" },
  new Car { id= 301, brand= "Toyota", name= "GR Yaris 1st Edition RZ High performance", category="N 300" },
  new Car { id= 302, brand= "Toyota", name= "MR2 GT-S", category= "N 200" },
  new Car { id= 303, brand= "Toyota", name= "Sports 800", category= "N 100" },
  new Car { id= 304, brand= "Toyota", name= "Sprinter Trueno 3door 1600GT APEX (AE86)", category= "N 100" },
  new Car { id= 305, brand= "Toyota", name= "Supra 3.0GT Turbo A", category= "N 300" },
  new Car { id= 306, brand= "Toyota", name= "Supra RZ", category= "N 300" },
  new Car { id= 307, brand= "Toyota", name= "Toyota 2000GT", category= "N 200" },
  new Car { id= 308, brand= "Toyota", name= "TOYOTA 86 Gr.4", category= "Gr.4" },
  new Car { id= 309, brand= "Toyota", name= "TOYOTA 86 Gr.B Rally Car", category= "Gr.B Rally" },
  new Car { id= 310, brand= "Toyota", name= "TOYOTA 86 GT", category= "N 200" },
  new Car { id= 311, brand= "Toyota", name= "Toyota FT-1", category= "Gr.X" },
  new Car { id= 312, brand= "Toyota", name= "Toyota FT-1 Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 313, brand= "Toyota", name= "Toyota FT-1 Vision Gran Turismo (Gr.3)", category= "Gr.3" },
  new Car { id= 314, brand= "Toyota", name= "TOYOTA S-FR", category= "N 100" },
  new Car { id= 315, brand= "Toyota", name= "TOYOTA S-FR Racing Concept", category= "N 400" },
  new Car { id= 316, brand= "Toyota", name= "Toyota TS050 - Hybrid (Toyota Gazoo Racing)", category= "Gr.1" },
  new Car { id= 317, brand= "Toyota", name= "TS030 Hybrid", category= "Gr.1" },
  new Car { id= 318, brand= "Toyota", name= "Tundra TRD Pro", category= "N 400" },
  new Car { id= 319, brand= "Tesla Motors", name= "Model S Signature Performance", category= "Gr.X" },
  new Car { id= 320, brand= "TVR", name= "Tuscan Speed 6", category= "N 400" },
  new Car { id= 321, brand= "Volkswagen", name= "Golf I GTI", category= "N 100" },
  new Car { id= 322, brand= "Volkswagen", name= "Golf VII GTI", category= "N 200" },
  new Car { id= 323, brand= "Volkswagen", name= "GTI Roadster Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 324, brand= "Volkswagen", name= "GTI Supersport Vision Gran Turismo", category= "Gr.X" },
  new Car { id= 325, brand= "Volkswagen", name= "GTI Vision Gran Turismo (Gr.3)", category= "Gr.3" },
  new Car { id= 326, brand= "Volkswagen", name= "Sambabus Typ 2 (T1)", category= "N 100" },
  new Car { id= 327, brand= "Volkswagen", name= "Scirocco Gr.4", category= "Gr.4" },
  new Car { id= 328, brand= "Volkswagen", name= "Volkswagen 1200", category= "N 100" },
  new Car { id= 329, brand= "Volkswagen", name= "Volkswagen Beetle Gr.3", category= "Gr.3" },
  new Car { id= 330, brand= "Zagato", name= "IsoRivolta Zagato Vision Gran Turismo", category= "Gr.X" },
            
  };

            List<Track> trackList = new List<Track>{
new Track {
      distance= 7004,
      title= "spa",
      elevationChange=104,
      corners=21,
      longestStraight=751,
    },
    new Track {
      distance= 3602,
      title= "legunaSeca",
      elevationChange=55,
      corners=11,
      longestStraight=453,
    },
    new Track {
      distance=3809,
      title= "goodWood",
      elevationChange=10,
      corners=7,
      longestStraight=514,
    },
    new Track {
      distance= 4674,
      title= "autopolis",
      elevationChange= 52,
      corners= 18,
      longestStraight=902,
    },
    new Track {
      distance= 3022,
      title= "autopolisShortCourse",
      elevationChange=  0,
      corners=  0,
      longestStraight= 0,
    },
    new Track {
      distance= 4655,
      title= "circuitDeBarcelonaCatalunya",
      elevationChange= 30,
      corners= 16,
      longestStraight=1047,
    },
    new Track {
      distance= 4563,
      title= "fujiSpeedway",
      elevationChange= 40,
      corners= 16,
      longestStraight=1475,
    },
    new Track {
      distance= 4526,
      title= "fujiSpeedwayShort",
      elevationChange=  0,
      corners=  0,
      longestStraight= 0,
    },
    new Track {
      distance= 4318,
      title= "redBullRing",
      elevationChange= 65,
      corners= 10,
      longestStraight=939,
    },
    new Track {
      distance= 4526,
      title= "redBullRingShort",
      elevationChange=  0,
      corners=  0,
      longestStraight= 0,
    },
    new Track {
      distance= 13629,
      title= "circuitDeLaSarthe",
      elevationChange= 37,
      corners= 38,
      longestStraight=1679,
    },
    new Track {
      distance= 13567,
      title= "circuitDeLaSartheShort",
      elevationChange=  0,
      corners=  0,
      longestStraight= 0,
    },
    new Track {
      distance= 2045,
      title= "tskuba",
      elevationChange= 5,
      corners= 8,
      longestStraight=445,
    },
    new Track {
      distance= 5793,
      title= "autodromoNazionaleMonza",
      elevationChange= 13,
      corners= 11,
      longestStraight=938,
    },
    new Track {
      distance= 5755,
      title= "autodromoNazionaleMonzaShort",
      elevationChange= 13,
      corners= 11,
      longestStraight=938,
    },
    new Track {
      distance= 4309,
      title= "autodromoDeInterlagos",
      elevationChange= 44,
      corners= 15,
      longestStraight=589,
    },
    new Track {
      distance= 25378,
      title= "nurburgrig24",
      elevationChange= 300,
      corners= 89,
      longestStraight=2135,
    },
    new Track {
      distance= 20832,
      title= "nordschleife",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5148,
      title= "nurburgrigGp",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 3951,
      title= "willowSpringBig",
      elevationChange= 50,
      corners=10,
      longestStraight=756,
    },
    new Track {
      distance= 2675,
      title= "willowSpringStreet",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 1624,
      title= "willowSpringHorse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 2675,
      title= "willowSpringStreetReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 1624,
      title= "willowSpringHorseReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 3946,
      title= "brandsHatch",
      elevationChange= 35,
      corners=9,
      longestStraight=475,
    },
    new Track {
      distance= 1944,
      title= "brandsHatchIndy",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 6213,
      title= "mountPanorama",
      elevationChange= 174,
      corners=23,
      longestStraight=1916,
    },
    new Track {
      distance= 5807,
      title= "suzuka",
      elevationChange= 40,
      corners=20,
      longestStraight=1200,
    },
    new Track {
      distance= 2243,
      title= "suzukaEast",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5113,
      title= "sardegna",
      elevationChange= 38,
      corners=15,
      longestStraight=915,
    },
    new Track {
      distance= 3893,
      title= "sardegnaB",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 2661,
      title= "sardegnaC",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5113,
      title= "sardegnaReverse",
      elevationChange= 38,
      corners=15,
      longestStraight=915,
    },
    new Track {
      distance= 3893,
      title= "sardegnaBReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 2661,
      title= "sardegnaCReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 30283,
      title= "specialStageRouteX",
      elevationChange= 65,
      corners=2,
      longestStraight=12000,
    },
    new Track {
      distance= 9477,
      title= "sainteCroix",
      elevationChange= 44,
      corners=19,
      longestStraight=915,
    },
    new Track {
      distance= 7602,
      title= "sainteCroixB",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 10825,
      title= "sainteCroixC",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 9477,
      title= "sainteCroixReverse",
      elevationChange= 44,
      corners=19,
      longestStraight=915,
    },
    new Track {
      distance= 7602,
      title= "sainteCroixBReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 10825,
      title= "sainteCroixCReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4912,
      title= "kyotoDrivingPark",
      elevationChange= 38,
      corners=15,
      longestStraight=743,
    },
    new Track {
      distance= 1953,
      title= "kyotoDrivingParkMiyabi",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 6846,
      title= "kyotoDrivingParkFull",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4912,
      title= "kyotoDrivingParkReverse",
      elevationChange= 38,
      corners=15,
      longestStraight=743,
    },
    new Track {
      distance= 6846,
      title= "kyotoDrivingParkFullReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4405,
      title= "tokyoExpresswayCentralOuter",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4369,
      title= "tokyoExpresswayCentralInner",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 7301,
      title= "tokyoExpresswayEastOuter",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 7192,
      title= "tokyoExpresswayEastInner",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5201,
      title= "tokyoExpresswaySouthOuter",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 6560,
      title= "tokyoExpresswaySouthInner",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5209,
      title= "dragonTrail",
      elevationChange= 38,
      corners=18,
      longestStraight=653,
    },
    new Track {
      distance= 4352,
      title= "dragonTrailGardens",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5209,
      title= "dragonTrailReverse",
      elevationChange= 38,
      corners=18,
      longestStraight=653,
    },
    new Track {
      distance= 4352,
      title= "dragonTrailGardensReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5809,
      title= "autodromoLagoMaggioreGp",
      elevationChange= 74,
      corners=17,
      longestStraight=800,
    },
    new Track {
      distance= 1706,
      title= "autodromoLagoMaggioreCenter",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 3643,
      title= "autodromoLagoMaggioreEast",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4168,
      title= "autodromoLagoMaggioreWest",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 5809,
      title= "autodromoLagoMaggioreGpReverse",
      elevationChange= 74,
      corners=17,
      longestStraight=800,
    },
    new Track {
      distance= 1706,
      title= "autodromoLagoMaggioreCenterReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 3643,
      title= "autodromoLagoMaggioreEastReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 4168,
      title= "autodromoLagoMaggioreWestReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 900,
      title= "northernIsleSpeedway",
      elevationChange= 0,
      corners=4,
      longestStraight=134,
    },
    new Track {
      distance= 3200,
      title= "blueMoonSpeedway",
      elevationChange= 0,
      corners=3,
      longestStraight=1060,
    },
    new Track {
      distance= 3350,
      title= "blueMoonSpeedwayInA",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 2860,
      title= "blueMoonSpeedwayInB",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 3200,
      title= "blueMoonSpeedwayReverse",
      elevationChange= 0,
      corners=3,
      longestStraight=1060,
    },
    new Track {
      distance= 3350,
      title= "blueMoonSpeedwayInAReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 2860,
      title= "blueMoonSpeedwayInBReverse",
      elevationChange=  0,
      corners= 0,
      longestStraight= 0,
    },
    new Track {
      distance= 1665,
      title= "broadBeanRaceway",
      elevationChange= 0,
      corners=5,
      longestStraight=386,
    },
    new Track {
      distance= 1665,
      title= "broadBeanRacewayReverse",
      elevationChange= 0,
      corners=5,
      longestStraight=386,
    },
    new Track {
      distance= 5423,
      title= "alsace",
      elevationChange= 57,
      corners=15,
      longestStraight=450,
    },
    new Track {
      distance= 5423,
      title= "alsaceReverse",
      elevationChange= 57,
      corners=15,
      longestStraight=450,
    },
    new Track {
      distance= 6893,
      title= "fishermansRanch",
      elevationChange= 145,
      corners=40,
      longestStraight=434,
    },
    new Track {
      distance= 6893,
      title= "fishermansRanchReverse",
      elevationChange= 145,
      corners=40,
      longestStraight=434,
    },
    new Track {
      distance= 3310,
      title= "sardegna",
      elevationChange= 75,
      corners=12,
      longestStraight=298,
    },
    new Track {
      distance= 3310,
      title= "sardegnaReverse",
      elevationChange= 75,
      corners=12,
      longestStraight=298,
    },
    new Track {
      distance= 2990,
      title= "coloradoSprings",
      elevationChange= 15,
      corners=8,
      longestStraight=177,
    },
    new Track {
      distance= 2990,
      title= "coloradoSpringsReverse",
      elevationChange= 15,
      corners=8,
      longestStraight=177,
    }
            };
       
            for (int i = 0; i < challengeTypes.Count; i++)
            {
                //pick random track, random car anc random number
                Random r = new Random();
                int rInt = r.Next(lowerBound[i], upperBound[i]);  
                int valueToGrabTrack = r.Next(0, 81);
                int valueToGrabCar = r.Next(0, 329);


                string track = trackList[valueToGrabTrack].title;
                string carBrand = carList[valueToGrabCar].brand;
                string carName  = carList[valueToGrabCar].name;
                string fullName = carBrand + carName;
                        challengeData.Add(new ChallengeData
                         {
                            Track = track,
                            Car = fullName,
                            Target = rInt,
                            Type = challengeTypes[i],
                        });
            }

            return challengeData;
  
    
}
public class ChallengeData
{
    public string Track { get; set; }
    public string Car { get; set; }
    public int Target { get; set; }
    public string Type { get; set; }
}
 private class Car
{
    public int id { get; set; }
    public string brand { get; set; }
    public string name { get; set; }
    public string category { get; set; }
}
 private class Track
{
    public int distance { get; set; }
    public string title { get; set; }
    public int elevationChange { get; set; }
    public int corners { get; set; }
    public int longestStraight { get; set; }
}
}
};